version: "3"
services:
  java8:
    build: 
      context: ./java8
    image: seanly/toolset:java8
  docker:
    build: 
      context: ./docker
    image: seanly/toolset:docker
  docker-buildx:
    build: 
      context: ./docker-buildx
    image: seanly/toolset:docker-buildx
  vimrc:
    build: 
      context: ./vimrc
    image: seanly/toolset:vimrc
  helm:
    build: 
      context: ./helm
    image: seanly/toolset:helm
  kustomize:
    build: 
      context: ./kustomize
    image: seanly/toolset:kustomize
  kubectl:
    build: 
      context: ./kubectl
    image: seanly/toolset:kubectl
  restic:
    build: 
      context: ./restic
    image: seanly/toolset:restic
  rke:
    build: 
      context: ./rke
    image: seanly/toolset:rke
  dapper:
    build: 
      context: ./dapper
    image: seanly/toolset:dapper
  velero:
    build: 
      context: ./velero
    image: seanly/toolset:velero
  ossutil:
    build: 
      context: ./ossutil
    image: seanly/toolset:ossutil
  krew:
    build: 
      context: ./krew
    image: seanly/toolset:krew
  nerdctl:
    build: 
      context: ./nerdctl
    image: seanly/toolset:nerdctl
  mkcert:
    build: 
      context: ./mkcert
    image: seanly/toolset:mkcert
  jinja2-cli:
    build: 
      context: ./jinja2-cli
    image: seanly/toolset:jinja2-cli
  image-syncer:
    build: 
      context: ./image-syncer
    image: seanly/toolset:image-syncer
  confd:
    build: 
      context: ./confd
    image: seanly/toolset:confd
  helmfile:
    build: 
      context: ./helmfile
    image: seanly/toolset:helmfile
  kubebuilder:
    build: 
      context: ./kubebuilder
    image: seanly/toolset:kubebuilder
  forego:
    build: 
      context: ./forego
    image: seanly/toolset:forego
  oracle-jdk17:
    build: 
      context: ./oracle-jdk17
    image: seanly/toolset:oracle-jdk17
  oracle-jdk17-maven:
    build: 
      context: ./oracle-jdk17/maven
    image: seanly/toolset:oracle-jdk17-maven
