version: '3'

services:
  openldap:
    build:
      context: .
    container_name: openldap
    image: seanly/appset:openldap
    restart: unless-stopped
    ports:
      - 389:389
    volumes:
      - openldap-data:/data
    environment:
      OPENLDAP_SUFFIX: dc=opsbox
      OPENLDAP_DOMAIN: oes 
      OPENLDAP_ADMIN_PASSWORD: admin!23
      OPENLDAP_CONFIG_PASSWORD: admin!23
      OPENLDAP_LDAPADMIN_PASSWORD: admin!23

networks:
  default:
    name: opsbox-network
    external: true

volumes:
    openldap-data:
